---
- name: Windows Update Banco de Dados - Teste
  hosts: bd

  tasks:
  - name: Instala todos os updates e reinicia
    ansible.windows.win_updates:
     category_names: '*'
     reboot: yes
#      retries: 5
  - name: Reiniciar máquina
    win_reboot:
      reboot_timeout: 600